name: 'upload test report'
description: 'Uploads the GdUnit test reports'

inputs:
  report-name:
    description: 'Name of the report to be upload.'
    required: true
  project_dir:
    description: 'The working directory to collect the reports.'
    required: true
    default: './'

runs:
  using: composite
  steps:
    - name: 'Upload Test Artifacts'
      uses: actions/upload-artifact@v5
      with:
        retention-days: 10
        name: artifact_${{ inputs.report-name }}
        path: |
          ${{ inputs.project_dir }}reports/**
          /var/lib/systemd/coredump/**
          /var/log/syslog
