# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: github-actions
    directory: '.github/actions/check-coredump/'
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: github-actions
    directory: '.github/actions/godot-install/'
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: github-actions
    directory: '.github/actions/publish-test-report/'
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: github-actions
    directory: '.github/actions/upload-test-report/'
    schedule:
      interval: "weekly"
      day: "sunday"