name: 'GdUnit4 - Test Runner'
description: 'This is a GitHub action workflow for running GdUnit4 unit tests in Godot 4.x'
author: Mike Schulze <mikeschulze.lpz@kabelmail.de>

inputs:
  godot-version:
    description: 'The version of Godot in which the tests should be run.'
    required: true
    type: string
  godot-status:
    description: 'The Godot status (e.g., "standard", "rc1", "dev1")'
    required: false
    type: string
    default: 'standard'
  godot-net:
    description: 'Set to true for Godot .Net (C#).'
    required: false
    type: bool
    default: false
  version:
    description: 'The version of GdUnit4 to use. (e.g. "v4.2.0", "latest", "master").'
    required: false
    type: string
    default: master
  tests:
    description: 'The path to the directory containing test to execute.'
    required: true
    type: string
  timeout:
    description: 'The test execution timeout in minutes.'
    required: false
    type: int
    default: 10
  report-name:
    description: 'The name of the test report file.'
    required: false
    type: string
    default: 'test-report.xml'

outputs:
  artifactsPath:
    description: 'Path where the test artifacts are stored.'

branding:
  icon: 'refresh-cw'
  color: 'purple'

runs:
  using: 'composite'
  steps:

    - name: "Set Cache Name"
      shell: bash
      run: |
        if ${{inputs.godot-net == 'true'}}; then
            echo "CACHE_NAME=${{ runner.OS }}-Godot_v${{ inputs.godot-version }}-${{ inputs.godot-status-version }}_mono" >> "$GITHUB_ENV"
        else
            echo "CACHE_NAME=${{ runner.OS }}-Godot_v${{ inputs.godot-version }}-${{ inputs.godot-status-version }}" >> "$GITHUB_ENV"
        fi

    - name: "Build Cache"
      uses: actions/cache@v4
      id: godot-cache-binary
      with:
        path: '/home/runner/godot-linux'
        key: ${{ env.CACHE_NAME }}
        restore-keys: ${{ env.CACHE_NAME }}
        enableCrossOsArchive: true

    - name: 'Install Godot ${{ inputs.godot-version }}'
      if: steps.godot-cache-binary.outputs.cache-hit != 'true'
      uses: ./.github/actions/godot-install
      with:
        godot-version: ${{ inputs.godot-version }}
        godot-net: ${{ inputs.godot-net }}
        godot-status-version: ${{ inputs.godot-status }}
        install-path: '/home/runner/godot-linux'

    - name: 'Install gdUnit4 plugin - ${{ inputs.version }}'
      shell: bash
      run: |
          if ${{ inputs.version == 'latest' }}; then
            latest_version=$(git ls-remote --refs --tags https://github.com/MikeSchulze/gdUnit4 v* | sort -t '/' -k 3 -V | tail -n 1 | cut -d '/' -f 3)
            git clone --quiet --depth 1 --branch "${latest_version}" --single-branch https://github.com/MikeSchulze/gdUnit4 install-gdunit4
            echo -e "* GdUnit4 \e[34m${latest_version}\e[0m installed."
          else
            git clone --quiet --depth 1 --branch "${{ inputs.version }}" --single-branch https://github.com/MikeSchulze/gdUnit4 install-gdunit4
            echo -e "* GdUnit4 \e[34m${{ inputs.version }}\e[0m installed."
          fi
          mv ./install-gdunit4/addons/ ./addons/
          rm -rf ./addons/gdUnit4/test
          chmod +x ./addons/gdUnit4/runtest.sh

    - name: 'Update Project'
      if: ${{ !cancelled() }}
      shell: bash
      run: |
        if ${{ inputs.godot-net == 'true' }}; then
          dotnet restore
          dotnet build
        fi
        xvfb-run --auto-servernum /home/runner/godot-linux/godot -e --path . -s res://addons/gdUnit4/bin/ProjectScanner.gd --headless --audio-driver Dummy 2> /dev/null

    - name: 'test node.js stuff'
      env:
        GODOT_BIN: '/home/runner/godot-linux/godot'
      uses: actions/github-script@v7
      with:
        script: |
          const script = require('./.github/actions/unit-test/index.js')
          const args = {
            timeout: '${{ inputs.timeout }}',
            tests: '${{ inputs.tests }}'
          };

          await script(args);

    - name: 'Publish Unit Test Reports'
      if: ${{ !cancelled() }}
      uses: ./.github/actions/publish-test-report
      with:
        report-name: ${{ inputs.report-name }}

    - name: 'Upload Unit Test Reports'
      if: ${{ !cancelled() }}
      uses: ./.github/actions/upload-test-report
      with:
        report-name: ${{ inputs.report-name }}