name: 'GdUnit4 - Test Runner Action'
description: 'This GitHub Action automates the execution of GdUnit4 unit tests within the Godot Engine 4.x environment.'
author: Mike Schulze <mikeschulze.lpz@gmail.com>

inputs:
  godot-version:
    description: 'The version of Godot in which the tests should be run.'
    required: true
  godot-status:
    description: 'The Godot status (e.g., "stable", "rc1", "dev1")'
    required: false
    default: 'stable'
  godot-net:
    description: 'Set to true for Godot .Net (C#).'
    required: false
    default: 'false'
  godot-force-mono:
    description: 'Force test run to use Godot Mono version'
    required: false
    default: 'false'
  version:
    description: 'The version of GdUnit4 to use. (e.g. "v4.2.0", "latest", "master").'
    required: false
    default: latest
  dotnet-version:
    description: 'The used .NET version to run the test (e.g. "net7.0", "net8.0")'
    required: false
    default: net8.0
  console-verbosity:
    description: 'Console logger verbosity for C# tests (quiet|minimal|normal|detailed|diagnostic)'
    required: false
    default: 'minimal'
  paths:
    description: 'Comma-separated or newline-separated list of directories containing test to execute.'
    required: true
  arguments:
    description: 'Additional arguments to run GdUnit4. (e.g. "--verbose")'
    required: false
  timeout:
    description: 'The test execution timeout in minutes.'
    required: false
    default: '10'
  retries:
    description: 'The number of retries if the tests fail.'
    required: false
    default: '0'
  warnings-as-errors:
    description: 'Treat test warnings as errors (return code 101 will be treated as error)'
    required: false
    default: 'false'
  publish-report:
    description: 'Enable disable to publish the report. To disable to run on forked repositories.'
    required: false
    default: 'true'
  upload-report:
    description: 'Whether the report & logs should be uploaded.'
    required: false
    default: 'true'
  project_dir:
    description: 'The project directory in which the action is to be executed. The specified directory must end with a path separator. e.g. ./MyProject/'
    required: false
    default: './'
  report-name:
    description: 'The name of the test report file.'
    required: false
    default: 'test-report.xml'

outputs:
  exit_code:
    description: 'The exit code from the test run'
    value: ${{ steps.test-run.outputs.exit_code }}

  version_check_exit_code:
    description: 'The exit code from the version compatibility check'
    value: ${{ steps.version_check.outputs.exit_code }}

branding:
  icon: 'refresh-cw'
  color: 'purple'

runs:
  using: 'composite'
  steps:
    # FIXME: workaround until will be merged: https://github.com/actions/runner/pull/1684
    - shell: bash
      run: |
        echo "GITHUB_ACTION_PATH: ${GITHUB_ACTION_PATH}"
        [ -d ./.gdunit4_action ] || (mkdir -p ./.gdunit4_action/ && cp -r $GITHUB_ACTION_PATH/.gdunit4_action/* ./.gdunit4_action/)      

    # Determine the actual GdUnit4 version that will be used
    - name: 'Determine GdUnit4 Version'
      id: determine-version
      uses: ./.gdunit4_action/versioning
      with:
        version: ${{ inputs.version }}
        project_dir: ${{ inputs.project_dir }}

    # Verify version compatibility
    - name: 'Check Version Compatibility'
      uses: ./.gdunit4_action/versioning/check
      id: version_check
      with:
        godot-version: ${{ inputs.godot-version }}
        gdunit-version: ${{ env.GDUNIT_VERSION }}

    - name: 'Set Cache Name'
      shell: bash
      run: |
        if ${{inputs.godot-net == 'true' || inputs.godot-force-mono == 'true'}}; then
            echo "CACHE_NAME=${{ runner.OS }}-Godot_v${{ inputs.godot-version }}-${{ inputs.godot-status }}-${{ inputs.dotnet-version }}" >> "$GITHUB_ENV"
        else
            echo "CACHE_NAME=${{ runner.OS }}-Godot_v${{ inputs.godot-version }}-${{ inputs.godot-status }}" >> "$GITHUB_ENV"
        fi

        echo "RUN_GDSCRIPT_TESTS=${{inputs.godot-net == 'false'}}" >> "$GITHUB_ENV"

    - name: 'Build Cache'
      uses: actions/cache@v4
      id: godot-cache-binary
      with:
        path: '/home/runner/godot-linux'
        key: ${{ env.CACHE_NAME }}
        restore-keys: ${{ env.CACHE_NAME }}
        enableCrossOsArchive: true

    - name: 'Install Godot ${{ inputs.godot-version }}'
      if: steps.godot-cache-binary.outputs.cache-hit != 'true'
      uses: ./.gdunit4_action/godot-install
      with:
        godot-version: ${{ inputs.godot-version }}
        godot-net: ${{inputs.godot-net == 'true' || inputs.godot-force-mono == 'true'}}
        godot-status-version: ${{ inputs.godot-status }}
        install-path: '/home/runner/godot-linux'

    - name: 'print restored version - ${{ inputs.godot-version }}'
      shell: bash
      run: |
        /home/runner/godot-linux/godot --version

    - name: 'Install gdUnit4 plugin - ${{ env.GDUNIT_VERSION }}'
      # We only install the plugin if required, for c# test is not need to install the plugin
      if: ${{ steps.version_check.outcome == 'success' && !cancelled() && env.RUN_GDSCRIPT_TESTS == 'true' }}
      shell: bash
      run: |
        
        echo -e "\e[33m Change to project directory: ${{ inputs.project_dir }} \e[0m"
        cd "${{ inputs.project_dir }}"

        if ${{ inputs.version == 'installed' }}; then
          echo -e "\e[33m Info: Using the installed GdUnit4 plugin version ${{ env.GDUNIT_VERSION }}. \e[0m"
          chmod +x ./addons/gdUnit4/runtest.sh
          exit 0
        fi

        # Prepare install
        CLONE_DIR="./.gdunit4-version-${{ inputs.version }}"
        if [[ -d "${CLONE_DIR}" ]]; then
          mv "${CLONE_DIR}" ./.install-gdunit4
        else
          git clone --quiet --depth 1 --branch ${{ env.GDUNIT_VERSION }} --single-branch https://github.com/MikeSchulze/gdUnit4 ./.install-gdunit4
        fi

        # Remove test if no self test requested
        if [[ -d ./.install-gdunit4/addons/gdUnit4/test && ! "${{ env.GDUNIT_SELFTEST }}" ]]; then
          echo "Delete 'addons/gdUnit4/test'"
          rm -rf ./.install-gdunit4/addons/gdUnit4/test
        fi
        
        # Delete first possible outdated artifacts
        if [[ -d ./addons/gdUnit4 ]]; then
          echo -e "\e[33m Info: Found a previous installation of GdUnit4, deleting it now. \e[0m"
          rm -rf ./addons/gdUnit4
        fi

        # Install requested gdUnit4 version into current project
        echo -e "\e[34m Install GdUnit4 \e[92m${{ env.GDUNIT_VERSION }} \e[34m plugin in the project \e[0m"
        mkdir -p ./addons/gdUnit4/
        cp -R ./.install-gdunit4/addons/gdUnit4 ./addons
        chmod +x ./addons/gdUnit4/runtest.sh
        
        # Cleanup
        rm -rf ./.install-gdunit4
        
        echo -e "\e[34m Installed plugins\e[0m"
        echo -e "\e[34m -----------------\e[0m"
        ls --color=auto -lsA ./addons
        echo -e "\e[34m -----------------\e[0m"

    - name: 'Set .NET SDK version'
      if: ${{ steps.version_check.outcome == 'success' && !cancelled() && (inputs.godot-net == 'true' || inputs.godot-force-mono == 'true') }}
      shell: bash
      run: |
        sdk_version=$(echo "${{ inputs.dotnet-version }}" | sed 's/^net\([0-9]\.[0-9]\)$/\1.x/')
        echo "SDK_VERSION=$sdk_version" >> "$GITHUB_ENV"
        echo "Using .NET version: '$sdk_version'"

    - name: 'Setup .NET SDK'
      if: ${{ steps.version_check.outcome == 'success' && !cancelled() && (inputs.godot-net == 'true' || inputs.godot-force-mono == 'true') }}
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '${{ env.SDK_VERSION }}'

    - name: 'Restore .Net Project'
      if: ${{ steps.version_check.outcome == 'success' && !cancelled() && (inputs.godot-net == 'true' || inputs.godot-force-mono == 'true') }}
      shell: bash
      run: |
        cd "${{ inputs.project_dir }}"
        
        # for gdunit version less than 4.2.2 we need to load api version 4.2.1.1
        gdUnitVersion=$(echo "${{ inputs.version }}" | sed 's/^v//; s/\.//g')
        if [[ ${gdUnitVersion} < 422 ]]; then
          # install required packages
          echo "gdUnit4 version ${gdUnitVersion} less 4.2.2, update project to gdUnit4.api v4.2.1"
          dotnet add package gdUnit4.api --version 4.2.1
          dotnet add package gdUnit4.test.adapter --version 1.0.0
        fi
        
        dotnet --version
        dotnet build
        dotnet list package

    - name: 'Restore Godot project cache'
      if: ${{ steps.version_check.outcome == 'success' && !cancelled() }}
      env:
        GODOT_BIN: '/home/runner/godot-linux/godot'
      shell: bash
      run: |
        cd "${{ inputs.project_dir }}"
        echo -e "\e[94mStart of the recovery of the project cache ...\e[0m"
        $GODOT_BIN --path ./ -e --headless --quit-after 2000
        echo -e "\e[94mProject cache successfully restored.\e[0m"

    ## GDScript test run
    - name: 'Run GDScript Tests'
      id: test-run
      if: ${{ steps.version_check.outcome == 'success' && !cancelled() && env.RUN_GDSCRIPT_TESTS == 'true'}}
      env:
        GODOT_BIN: '/home/runner/godot-linux/godot'
      uses: actions/github-script@v8
      with:
        script: |
          const { runTests } = require('./.gdunit4_action/unit-test/index.js')
          const args = {
            project_dir: `${{ inputs.project_dir }}`,
            paths: `${{ inputs.paths }}`,
            arguments: `${{ inputs.arguments }}`,
            timeout: ${{ inputs.timeout }},
            retries: ${{ inputs.retries }},
            warningsAsErrors : ${{ inputs.warnings-as-errors }}
          };
          const exitCode =  await runTests(args, core);
          core.setOutput('exit_code', exitCode);

    - name: 'Publish GDScript Unit Test Reports'
      if: ${{ steps.version_check.outcome == 'success' && !cancelled() && inputs.publish-report == 'true' && env.RUN_GDSCRIPT_TESTS == 'true'}}
      uses: ./.gdunit4_action/publish-test-report
      with:
        project_dir: ${{ inputs.project_dir }}
        report-name: ${{ inputs.report-name }}
        reporter: java-junit

    ## .Net test run
    - name: 'Run C# Tests'
      if: ${{ steps.version_check.outcome == 'success' && !cancelled() && env.RUN_GDSCRIPT_TESTS == 'false' }}
      env:
        GODOT_BIN: '/home/runner/godot-linux/godot'
      shell: bash
      run: |
        cd "${{ inputs.project_dir }}"
        # test if a .runsettings file exists, if not use the action provided default .runsettings
        if [ -f .runsettings ]; then
          echo "Found '.runsettings' file."
        else
          echo "No project specific '.runsettings' found, using action default '.runsettings'"
          cp $GITHUB_ACTION_PATH/.gdunit4_action/.runsettings .
        fi
        xvfb-run --auto-servernum dotnet test --no-build --settings .runsettings --results-directory ./reports --logger "console;verbosity=${{ inputs.console-verbosity }}" --logger "trx;LogFileName=results.xml" -- GdUnit4.Parameters="--audio-driver Dummy --display-driver x11 --rendering-driver opengl3 --screen 0 ${{ inputs.arguments }}"

    - name: 'Publish .Net Unit Test Reports'
      if: ${{ steps.version_check.outcome == 'success' && !cancelled() && inputs.publish-report == 'true' && env.RUN_GDSCRIPT_TESTS == 'false' }}
      uses: ./.gdunit4_action/publish-test-report
      with:
        project_dir: ${{ inputs.project_dir }}
        report-name: ${{ inputs.report-name }}
        reporter: dotnet-trx

    ## Finally upload the test result artifacts
    - name: 'Upload Unit Test Reports'
      if: ${{ steps.version_check.outcome == 'success' && !cancelled() && inputs.upload-report == 'true' }}
      uses: ./.gdunit4_action/upload-test-report
      with:
        project_dir: ${{ inputs.project_dir }}
        report-name: ${{ inputs.report-name }}
