name: publish-test-report
description: 'Publishes the GdUnit test results'

inputs:
  report-name:
    description: 'Name of the check run which will be created.'
    required: true
  project_dir:
    description: 'The working directory to collect the results.'
    required: true
    default: './'
  reporter:
    description: 'The report format to build the report'
    required: false
    default: 'java-junit'
  

runs:
  using: composite
  steps:
    - name: 'Publish Test Results'
      uses: dorny/test-reporter@v1.9.1
      with:
        name: ${{ inputs.report-name }}
        path: '${{ inputs.project_dir }}reports/**/results.xml'
        reporter: ${{ inputs.reporter }}
        fail-on-error: 'false'
        fail-on-empty: 'false'
