name: ci-dev
run-name: ${{ github.head_ref || github.ref_name }}-ci-dev

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.jpg'
      - '**.png'
      - '**.md'
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 7" # At 12:00 AM, only on Sunday

concurrency:
  group: ci-dev-${{ github.event.number }}
  cancel-in-progress: true

jobs:

  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        godot-version: ['4.2', '4.2.1']
        godot-status: ['stable']
        godot-net: ['', '.Net']
        version: ['latest']


    permissions:
      actions: write
      checks: write
      contents: write
      statuses: write

    name: GdUnit4 '${{ matrix.version }}' - Godot_${{ matrix.godot-version }}-${{ matrix.godot-status }}${{ matrix.godot-net }}

    steps:
      - name: 'Checkout gdUnit4-action'
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: 'Install test project'
        shell: bash
        run: |
          mv -f .github/workflows/resources/* .

      - name: 'Test gdUnit4-action@master: GdUnit4 ${{ matrix.version }} - Godot_${{ matrix.godot-version }}-${{ matrix.godot-status }}'
        if: ${{ matrix.godot-net == '' }}
        timeout-minutes: 5
        uses: ./
        with:
          godot-version: ${{ matrix.godot-version }}
          godot-status: ${{ matrix.godot-status }}
          version: ${{ matrix.version }}
          paths: |
            res://tests/
            res://tests-2/
          timeout: 2
          report-name: report_gdUnit4-${{ matrix.version }}_Godot${{ matrix.godot-version }}-${{ matrix.godot-status }}.xml

      - name: 'Test gdUnit4-action@master: GdUnit4 ${{ matrix.version }} - Godot_${{ matrix.godot-version }}-${{ matrix.godot-status }}-net'
        if: ${{ matrix.godot-net == '.Net' }}
        timeout-minutes: 5
        uses: ./
        with:
          godot-version: ${{ matrix.godot-version }}
          godot-status: ${{ matrix.godot-status }}
          godot-net: true
          version: ${{ matrix.version }}
          paths: 'res://tests/mono'
          timeout: 2
          retries: 3 # We have set the number of repetitions to 3 because Godot mono randomly crashes during C# tests
          report-name: report_gdUnit4-${{ matrix.version }}_Godot${{ matrix.godot-version }}-${{ matrix.godot-status }}-net.xml


  finalize:
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    name: 'Final Results'
    needs: [unit-tests]
    steps:
      - run: exit 1
        if: >-
          ${{
               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
          }}
